### ISSUE TITLE
partial commit

### ISSUE THREAD

**Issue by XiaoLiuAI** [jiangxin/gistore#1]
你好
如果我希望暂时只备份目标文件价下某一个子文件（夹），忽略其它子文件（夹）的变化，该如何用gistore实现？
同时，我对gistore的理解是，gistore在备份文件夹里建立了一系列git仓库，将目标文件夹中的数据备份到备份文件夹里。但是对于git来说，仓库是放在目标文件夹下的，不存在多文件夹备份。这么一来，该如何从gitstore储存的仓库里还原备份文件？

**Comment by jiangxin** [comment]
使用  `gistore add <dir>`  添加要备份的子目录，不要添加父目录，
或者用 `gistore rm <dir>` 删除登机的父目录。后台是通过 git 忽略
实现的，将 GIT_DIR 设置为根目录，忽略掉备份数据之外的所有
内容。

不过我现在使用 bup 和开发的 redmine 插件（有时间我整理之后开源）
进行备份，不再使用 gistore 了。因为对于大量的备份数据，git 吃不消。
